version: "3.9"

services:

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: subscriptions
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file:
      - .env